// <auto-generated />
namespace JobPosting.DAL.JBMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initialconfig3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialconfig3));
        
        string IMigrationMetadata.Id
        {
            get { return "201802081601109_initialconfig3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
